apiVersion: batch/v1
kind: CronJob
metadata:
  name: remove-ingress-cronjob-$(deploymentName)
spec:
  schedule: "$(useTimeMinute) $(currentHour) */1 * *"
  successfulJobsHistoryLimit: 0
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: account-service
          restartPolicy: OnFailure
          containers:
          - name: remove-host-container
            image: bitnami/kubectl
            command:
              - "sh"
              - "-c"
              - |
                export PATH=$PATH:/shared/usr/bin

                # Run kubectl commands with debugging statements
                INDEX=$(kubectl get ingress ingress-route -o=json | jq -r '.spec.rules[].host' | grep -n "$(deploymentName)api.minhnhut.online" | cut -d: -f1)
                echo "INDEX: $INDEX"
                kubectl patch ingress ingress-route -n default --type json -p "[{'op': 'remove', 'path': '/spec/rules/$((INDEX-1))'}]" 
                sleep 300 &&
                kubectl delete cronjob remove-ingress-cronjob-$(deploymentName)
            volumeMounts:
              - name: shared-volume
                mountPath: /shared
          initContainers:
          - name: install-tools
            image: debian:stable-slim
            command: ["/bin/sh", "-c"]
            args:
              - apt-get update && apt-get install -y jq
            volumeMounts:
            - name: shared-volume
              mountPath: /shared
          volumes:
          - name: shared-volume
            emptyDir: {}
